# These are supported funding model platforms

patreon: tunnckoCore # Replace with a single Patreon username
ko_fi: tunnckoCore # Replace with a single Ko-fi username

# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom:
  - https://gumroad.com/l/tunnckoCoreRecurringDonation
  - https://gumroad.com/l/tunnckoCorePatronLicense
# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# open_collective: # Replace with a single Open Collective username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
