name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Tests
    env:
      CI: true
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    strategy:
      matrix:
        platform: [ubuntu-18.04, macos-latest]
        node-version: [10.x, 12.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        name: Set Node.js v${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      # - uses: actions/cache@master
      #   name: Cache dependencies
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          yarn --prefer-offline --frozen-lockfile || yarn --frozen-lockfile || yarn
      - name: Run Tests
        run: yarn test
      # - name: Upload coverage to Codecov
      #   run: bash <(curl -s https://codecov.io/bash) -C $GITHUB_SHA -B ${GITHUB_REF#refs/heads/} -Z

  # typescript:
  #   name: TypeScript
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Set Node.js 10.x
  #       uses: actions/setup-node@master
  #       with:
  #         node-version: 10.x
  #     - name: Cache Dependencies
  #       uses: actions/cache@master
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-
  #     - name: Install Dependencies
  #       run: yarn
  #     - name: Check Types
  #       run: yarn tsc

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        name: Set Node.js v10.x
        with:
          node-version: 10.x
      # - uses: actions/cache@master
      #   name: Cache dependencies
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          yarn --prefer-offline --frozen-lockfile || yarn --frozen-lockfile || yarn
      - name: Run ESLint
        run: yarn eslint . --fix --quiet --format codeframe
